<?php

namespace ContainerLkW2wyv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HgeVi0OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hgeVi0O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hgeVi0O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eventplace' => ['privates', '.errored..service_locator.hgeVi0O.App\\Entity\\Eventplace', NULL, 'Cannot autowire service ".service_locator.hgeVi0O": it references class "App\\Entity\\Eventplace" but no such service exists.'],
            'eventplaceRepository' => ['privates', 'App\\Repository\\EventplaceRepository', 'getEventplaceRepositoryService', true],
        ], [
            'eventplace' => 'App\\Entity\\Eventplace',
            'eventplaceRepository' => 'App\\Repository\\EventplaceRepository',
        ]);
    }
}
