<?php

namespace ContainerLkW2wyv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VBenu7kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VBenu7k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VBenu7k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'event' => ['privates', '.errored..service_locator.VBenu7k.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.VBenu7k": it references class "App\\Entity\\Event" but no such service exists.'],
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'event' => 'App\\Entity\\Event',
            'eventRepository' => 'App\\Repository\\EventRepository',
            'slugger' => '?',
        ]);
    }
}
