<?php

namespace ContainerLkW2wyv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventplaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hgeVi0O.App\Entity\Eventplace' shared service.
     *
     * @return \App\Entity\Eventplace
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.hgeVi0O": it references class "App\\Entity\\Eventplace" but no such service exists.');
    }
}
