<?php

namespace ContainerRvxb6SA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J1ZsHCTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j1ZsHCT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j1ZsHCT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eventplace' => ['privates', '.errored..service_locator.j1ZsHCT.App\\Entity\\Eventplace', NULL, 'Cannot autowire service ".service_locator.j1ZsHCT": it references class "App\\Entity\\Eventplace" but no such service exists.'],
        ], [
            'eventplace' => 'App\\Entity\\Eventplace',
        ]);
    }
}
