<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLkW2wyv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLkW2wyv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLkW2wyv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLkW2wyv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLkW2wyv\App_KernelDevDebugContainer([
    'container.build_hash' => 'LkW2wyv',
    'container.build_id' => '39d3d3c4',
    'container.build_time' => 1682361604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLkW2wyv');
